# Generated by Django 2.1 on 2018-08-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
