# Generated by Django 2.1 on 2018-08-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_url',
            new_name='image',
        ),
    ]
